### ISSUE TITLE
[论文笔记](MobileNet V2)Inverted Residuals and Linear Bottlenecks: Mobile Networks for Classification, Detection and Segmentation | 萧爽楼

### ISSUE THREAD

**Issue by ddlee-cn** [ddlee-cn/blog_ddlee_cc#2]
https://blog.ddlee.cn/2018/01/18/%E8%AE%BA%E6%96%87%E7%AC%94%E8%AE%B0-Inverted-Residuals-and-Linear-Bottlenecks-Mobile-Networks-for-Classification-Detection-and-Segmentation/

**Comment by lhCheung1991** [comment]
"manifold of interest", 这个诡异的词真是理解得很艰难

**Comment by ddlee-cn** [comment]
是，术语定义不清，没有通用的描述。

**Comment by lxtGH** [comment]
感谢，讲的很清楚！！我复现了一发。不知对不对呢https://github.com/lxtGH/MobileNet_v1_v2_pytorch

**Comment by lhCheung1991** [comment]
@ddlee96
还是很棒的, 有理有据.
