### ISSUE TITLE
关于 | 萧爽楼

### ISSUE THREAD

**Issue by ddlee-cn** [ddlee-cn/blog_ddlee_cc#44]
https://blog.ddlee.cn/About/

**Comment by alyato** [comment]
rss 不可用。谢谢。

**Comment by ddlee-cn** [comment]
@alyato 页面上发懒没有加上.xml扩展，你可以试下：https://blog.ddlee.cn/atom.xml
或者用feedburner的链接：http://feeds.feedburner.com/ddlee_blog
谢谢提醒。

**Comment by alyato** [comment]
谢谢。可以了。

David D. Lee <notifications@github.com> 于2018年7月31日周二 下午10:01写道：

**Comment by alyato** [comment]
萧兄，你的具体文章不能评论，例如https://blog.ddlee.cn/posts/bfb815cf/，https://blog.ddlee.cn/posts/ad2d3bed/ 这两篇，
提示Error: Comments Not Initialized
但是在此页面可以评论。
————————————————————
另外对于你写的论文心得，我是非常赞成。
搞科研阅读文献是真的很重要，你已经写了。
现在想想，有些老师都不交，不是在培养学生，而是在利用学生。
萧兄，你能做出总结真的是很重要，因为观念一定要厘清。
谢谢你的分享。

**Comment by ddlee-cn** [comment]
@alyato 是这样的，这个评论系统是基于GitHub Issue的gitment，你说的这个Error是指还没有人提出关于这篇文章的Issue，如果保持Github的登录状态的话，可以找到一个Initialize Comment的按钮，它会以你的名义在我伺服网站的GitHub Repo (https://github.com/ddlee96/blog_ddlee_cn) 下提出一个带文章链接标签的Issue (https://github.com/ddlee96/blog_ddlee_cn/issues/53) 。我其实回复你也是在GitHub Issue这边处理的。

感谢你的反馈，共勉！
